wr("1_status", "restart")
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/episode1/choices/37/go_for_ellegaard.pmp', buttons.r, true, 'assets/video/episode1/choices/37/go_for_ellegaard.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/credits/ep1.pmp', buttons.start, true, 'assets/video/credits/ep1.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
dofile("assets/misc/pause.lua")