wr("3_status", "restart")
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/episode3/gabriel/choices/18/ellegaard/2/please_dont_die.pmp', buttons.r, true, 'assets/video/episode3/gabriel/choices/18/ellegaard/2/please_dont_die.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/credits/ep3.pmp', buttons.r, true, 'assets/video/credits/ep3.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
