wr("3_status", "restart")
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/episode3/gabriel/choices/18/magnus/2/this_armor_is_yours.pmp', buttons.r, true, 'assets/video/episode3/gabriel/choices/18/magnus/2/this_armor_is_yours.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/credits/ep3.pmp', buttons.start, true, 'assets/video/credits/ep3.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
