wr("2_status", "restart")
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/episode2/petra/5/be_careful.pmp', buttons.r, true, 'assets/video/episode2/petra/5/be_careful.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
PMP.setVolume(pmpvolume)
PMP.playEasy('assets/video/credits/ep2.pmp', buttons.r, true, 'assets/video/credits/ep2.srt', font, subssize, "#FFFFFF", "#000000/150", subs)
